### ISSUE TITLE
XMusic on Windows shows 2 additional files

### ISSUE THREAD

**Issue by kosmas12** [kosmas12/xmusic#3]
On Windows, when in the file picker, it seems to show 2 files called . and .. with no extension (or maybe the file names are extensions themselves) but this shouldn't be happening. They don't cause any issues with XMusic, unless you select to play them, where a segfault is caused. The problem doesn't appear on Linux or Xbox, and it also isn't currently known if the problem lies on XMusic's less-than-average error checking, or the FilesystemX submodule itself. My current recommended way to counter this problem is to filter the files I allow the user to pick using FilesystemX's getExt() function (and this solution is soon to be implemented in a PR).

**Comment by ExoSkye** [comment]
. is the current directory and .. is the previous directory so the segfaulting makes sense
I'll fix filesystemX so it dosen't display those files

**Comment by ExoSkye** [comment]
Actually does xmusic have a way to go back one directory?

**Comment by kosmas12** [comment]
@ProtoByter At least currently, XMusic has no way to traverse directories, it doesn't have the ability to go back

**Comment by kosmas12** [comment]
Since a fix for this was implemented on FilesystemX before implementing the workaround in a PR, I'm closing this issue without a PR
